name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build notely
        run: ./scripts/buildprod.sh

      - name: Set up env vars
        run: |
          echo "${{ secrets.ENV }}" > .env
          while IFS='=' read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
          done < .env

      - name: Build & push to GCR
        run: |
          gcloud builds submit --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$TAG .

